config/routes.rb
Rails.application.routes.draw do
  # Method of Order_Item and Orders_items
  post 'order_items' => "order_items#create"
  delete 'order_items/:id' => "order_items#destroy"
  get 'orders/:id' => "orders#show", as: "orders"
  # Method Routes of Checkouts
  resources :products, only: [:index]
  resources :checkout, only:[:index, :create]
  resources :shops, only:[:index, :show, :create]
  devise_for :users

  root "shops#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items
	scope :unpaid, ->{where completed_at: false }
	scope :paid,   ->{where completed_at: true }

	private

	def add_product(product_id)
		current_item = order_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = order_items.build(:product_id => product_id)
		end
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :cart_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable
	has_one :order, ->{unpaid}, class_name: Order.name
	has_many :unpaid_items, through: :order, source: :order_items
	has_many :unpaid_products, through: :unpaid_items, source: :product

	has_many :orders, -> { paid }, class_name: Order.name
	has_many :order_items, through: :orders
	has_many :products, through: :order_items, source: :product
	has_many :paid_products, through: :order_items, source: :product
	PASSWORD_FORMAT = /\A
		(?=.{8,})          # Must contain 8 or more characters
		(?=.*\d)           # Must contain a digit
		(?=.*[a-z])        # Must contain a lower case character
		(?=.*[A-Z])        # Must contain an upper case character
		(?=.*[[:^alnum:]]) # Must contain a symbol
	/x
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	validates :encrypted_password,
		presence: true,
		length: { in: Devise.password_length },
		format: { with: PASSWORD_FORMAT },
		confirmation: true,
		on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def not_found
	    raise ActionController::RoutingError.new('Not Found')
	rescue
	    render file: "#{Rails.root}/public/404", status: :not_found
	end

	private
	def current_order
		if session[:order_id]
	  		order = Order.find_by(:id => session[:order_id])
	  		if order.present?
	  			@current_order = order
	  		else
	  			session[:order_id] = nil
	  		end
		end
		if session[:order_id] == nil
			@current_order = Order.create(user_id: current_user.id, completed_at: false)
		end
	end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
	def index
		@checkout = Checkout.new
	end

	def create
		@checkout = Checkout.new(checkout_params)
		if @checkout.save
	      	CheckoutMailer.with(checkout: @checkout).new_checkout_email.deliver_later
	      	url = 'http://localhost:3000/rails/mailers/checkout_mailer/new_checkout_email.txt?locale=en'
			redirect_to url, notice: 'Payment method was successfully created.'
		else
			render index
		end
	end

	private

	def checkout_params
    	params.require(:checkout).permit(:name, :address, :phone, :message, :email)
	end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_quantity

  def create
    @order = current_order
    product = Product.find(params[:product_id])
    if product.blank?
      redirect_to cart_items_path, alert: "Product not found"
    end
    @order_item = OrderItem.create(product_id: product.id, order_id: current_order.id)
    if @order_item.save
      redirect_to orders_path(current_order.id), notice: "Successly add product to cart"
    else
      render :new, alert: "Unsuccessful to add products"
    end
  end

  # DELETE /order_items/products/1
  def destroy
    begin
      current_user.order.order_items.find_by!(id: params[:id]).destroy
    rescue
      redirect_to orders_path, alert: 'Not Found'
    end
  end

  private
    def set_quantity
      params.permit(:quantity)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_filter :current_order, only: [:show, :create]

  def show
    @orders = Order.all
  end

  # DELETE /orders/1.json
  def destroy
    @order = @current_order
    @order.destroy
    session[:order_id] = nil
    redirect_to root_path
  end

  private

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:user_id, :completed_at)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product =  Product.find(params[:product_id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id]) rescue not_found
	end

	private
	def add_quantity
		@order_item = OrderItem.find(params[:id])
		@order_item.quantity += 1
		@order_item.save
		redirect_to orders_path(@current_order)
	end

	def reduce_quantity
	  @order_item = OrderItem.find(params[:id])
	  if @order_item.quantity > 1
	  	@order_item.quantity -= 1
	  end
	  @order_item.save
	  redirect_to orders_path(@current_order)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/checkout/index.html.erb
<section class="testimonial py-5" id="testimonial">
    <div class="container">
        <div class="row ">
            <div class="col-md-4 py-5 bg-primary text-white text-center ">
                <div class=" ">
                    <div class="card-body">
                        <img src="http://www.ansonika.com/mavia/img/registration_bg.svg" style="width:30%">
                        <h2 class="py-3">Checkout Method</h2>
                        <p>Tation argumentum et usu, dicit viderer evertitur te has. Eu dictas concludaturque usu, facete detracto patrioque an per, lucilius pertinacia eu vel.
						</p>
                    </div>
                </div>
            </div>
            <div class="col-md-8 py-5 border">
                <h4 class="pb-4">Personal information of customers</h4>
				<%= form_for :checkout do |f| %>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                          <%= f.text_field :name, :class => 'form-control', placeholder: "Please enter your name" %>
                        </div>
                        <div class="form-group col-md-6">
							<%= f.text_field :email, :value => current_user.email, readonly: :true, :class => 'form-control' %>
                        </div>
                      </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                        	<%= f.text_field :address, :class => 'form-control', placeholder: "Address of your" %>
                        </div>
                        <div class="form-group col-md-6">
                            <%= f.number_field :phone, :class => 'form-control', placeholder: "Your number" %>
                        </div>
                        <div class="form-group col-md-12">
                        	<%= f.text_field :message, :class => 'form-control' %>
                        </div>
                    </div>
                    <div class="form-row">
                        <%= f.submit :submit, class: 'btn btn-success' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/_form.html.erb
<%= form_with(model: order_item, local: true) do |form| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
        <% order_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :completed_at %>
    <%= form.check_box :completed_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<div class="container">
   <div class="card shopping-cart">
            <div class="card-header bg-dark text-light">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Shipping cart
                <a href="" class="btn btn-outline-info btn-sm pull-right">Continiu shopping</a>
                <div class="clearfix"></div>
            </div>
            <div class="card-body">
                    <!-- PRODUCT -->
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-2 text-center">
                                <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew" width="120" height="80">
                        </div>
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                            <h4 class="product-name"><strong>Product Name</strong></h4>
                            <h4>
                                <small>Product description</small>
                            </h4>
                        </div>
                        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                            <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                                <h6><strong>25.00 <span class="text-muted">x</span></strong></h6>
                            </div>
                            <div class="col-4 col-sm-4 col-md-4">
                                <div class="quantity">
                                    <input type="button" value="+" class="plus">
                                    <input type="number" step="1" max="99" min="1" value="1" title="Qty" class="qty"
                                           size="4">
                                    <input type="button" value="-" class="minus">
                                </div>
                            </div>
                            <div class="col-2 col-sm-2 col-md-2 text-right">
                                <button type="button" class="btn btn-outline-danger btn-xs">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- END PRODUCT -->
                    <!-- PRODUCT -->
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-2 text-center">
                                <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew" width="120" height="80">
                        </div>
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                            <h4 class="product-name"><strong>Product Name</strong></h4>
                            <h4>
                                <small>Product description</small>
                            </h4>
                        </div>
                        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                            <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                                <h6><strong>25.00 <span class="text-muted">x</span></strong></h6>
                            </div>
                            <div class="col-4 col-sm-4 col-md-4">
                                <div class="quantity">
                                    <input type="button" value="+" class="plus">
                                    <input type="number" step="1" max="99" min="1" value="1" title="Qty" class="qty"
                                           size="4">
                                    <input type="button" value="-" class="minus">
                                </div>
                            </div>
                            <div class="col-2 col-sm-2 col-md-2 text-right">
                                <button type="button" class="btn btn-outline-danger btn-xs">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- END PRODUCT -->
                <div class="pull-right">
                    <a href="" class="btn btn-outline-secondary pull-right">
                        Update shopping cart
                    </a>
                </div>
            </div>
            <div class="card-footer">
                <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
                    <div class="row">
                        <div class="col-6">
                            <input type="text" class="form-control" placeholder="cupone code">
                        </div>
                        <div class="col-6">
                            <input type="submit" class="btn btn-default" value="Use cupone">
                        </div>
                    </div>
                </div>
                <div class="pull-right" style="margin: 10px">
                    <a href="" class="btn btn-success pull-right">Checkout</a>
                    <div class="pull-right" style="margin: 5px">
                        Total price: <b>50.00€</b>
                    </div>
                </div>
            </div>
        </div>
</div>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order_item.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @order_item.completed_at %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>

app/views/orders/_cart.html.erb
<div class="row">
  <div class="col-12 col-sm-12 col-md-2 text-center">
    <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew" width="120" height="80">
  </div>
  <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
      <h4 class="product-name"><strong><%= @order.current_user.name %></strong></h4>
      <h4>
        <small>Product description</small>
      </h4>
  </div>
  <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
      <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
        <h6><strong><%= @order.current_user.price %> <span class="text-muted">x</span></strong></h6>
      </div>
      <div class="col-4 col-sm-4 col-md-4">
        <div class="quantity">
            <input type="button" value="+" class="plus">
            <input type="number" step="1" max="99" min="1" value="1" title="Qty" class="qty" size="4">
            <input type="button" value="-" class="minus">
        </div>
      </div>
      <div class="col-2 col-sm-2 col-md-2 text-right">
          <button type="button" class="btn btn-outline-danger btn-xs">
            <i class="fa fa-trash" aria-hidden="true"></i>
          </button>
      </div>
  </div>
</div>

app/views/orders/_order.html.erb
<div class="row">
  <div class="col-12 col-sm-12 col-md-2 text-center">
    <img class="img-responsive" src="http://placehold.it/120x80" alt="prewiew" width="120" height="80">
  </div>
  <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
    <h4 class="product-name"><strong><%= order.name %></strong></h4>
    <h4>
      <small>Product description</small>
    </h4>
  </div>
  <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
    <div class="col-4 col-sm-4 col-md-4">
      <div class="quantity">
        <% set_quantity = current_user.unpaid_items.find(current_user.order.id) %>
        <%= number_field_tag 'quantity', value: set_quantity.quantity %>
      </div>
    </div>
    <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
      <h6><strong><%= order.price %><span class="text-muted"></span></strong></h6>
    </div>
    <div class="col-2 col-sm-2 col-md-2 text-right">
      <%= button_to 'Delete', {controller: :order_items, action: 'destroy', id: set_quantity.id , value: order.id}, method: :delete,data: { confirm: "Are you sure?"}, class: "btn btn-danger"  %>
    </div>
  </div>
</div>
<hr>

app/views/orders/show.html.erb
<div class="container">
  <div class="card shopping-cart">
    <div class="card-header bg-dark text-light">
      <i class="fa fa-shopping-cart" aria-hidden="true"></i>
      Shopping Cart
      <%= link_to "Continue Shopping", root_path, :class => 'btn btn-outline-info btn-sm pull-right' %>
      <div class="clearfix"></div>
    </div>
    <div class="card-body">
      <!-- PRODUCT -->
      <% @orders = current_user.unpaid_products%>
      <%= render partial: 'order', collection: @orders %>
      <!-- END PRODUCT -->
    </div>
    <div class="card-footer">
        <div class="pull-right" style="margin: 10px">
            <% user = current_user.id %>
            <%= link_to 'Checkout', checkout_index_path, :class => 'btn btn-success pull-right', method: :get %>
            <div class="pull-right" style="margin: 5px">
              Total price: <b>50.00€</b>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <%= if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/shops/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
	<div class="container">
	  <p class="m-0 text-center text-white">Copyright &copy; Phuong Website 2019</p>
	</div>
</footer>

app/views/shops/_header.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to 'Rails Shop', root_path, :class => 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
			<li class="nav-item active">
				<%= link_to 'Home', root_path, :class => 'nav-link' %>
			</li>
			<% if current_user %>
				<li class="nav-item active">
					<%= link_to 'Logout', destroy_user_session_path, :class => 'nav-link', method: :delete %>
				</li>
			<% else %>
				<li class="nav-item">
					<%= link_to 'Sign Up', new_user_registration_path, :class => 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Login', new_user_session_path, :class => 'nav-link' %>
				</li>
			<% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/shops/_product.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
    <div class="card-body">
      <h4 class="card-title">
        <a href="#"><%= product.name %></a>
      </h4>
      <h5><%= number_to_currency(product.price) %></h5>
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
      <%= link_to 'Details',  shop_path(product.id), :class => 'btn btn-primary' %>
      <%= link_to 'Add to cart', order_items_path(product_id: product.id), :class => 'btn btn-success', method: :post %>
    </div>
    <div class="card-footer">
      <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
  <%= render 'shops/header' %>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Slogan</h1>
        <div class="list-group">
          <a href="#" class="list-group-item">Category 1</a>
          <a href="#" class="list-group-item">Category 2</a>
          <a href="#" class="list-group-item">Category 3</a>
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <%= image_tag ("fruit.jpg"), :class => "d-block img-fluid" %>
            </div>
            <div class="carousel-item">
              <%= image_tag ("cakes.jpg"), :class => "d-block img-fluid" %>
            </div>
            <div class="carousel-item">
              <%= image_tag ("coffee.jpg"), :class => "d-block img-fluid" %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="row">
          <%= render partial: 'product', collection: @products %>
        </div>
        <!-- /.row -->
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- Footer -->
  <%= render 'shops/footer' %>

app/views/shops/show.html.erb
<div class="container">
	<h1 class="my-4">
		<%= link_to 'Back To Shop', root_path %>
  	</h1>
  	<!-- Portfolio Item Row -->
  	<div class="row">
    	<div class="col-md-8">
      		<img class="img-fluid" src="http://placehold.it/750x500" alt="">
    	</div>
	    <div class="col-md-4">
			<h3 class="my-3"><%= @product.name %></h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
			<h3 class="my-3">Price</h3>
			<ul>
				<li><%= @product.price %></li>
			</ul>
	    </div>
	</div>

  	<!-- Related Projects Row -->
	<h3 class="my-4">Related Projects</h3>
  	<div class="row">
	    <div class="col-md-3 col-sm-6 mb-4">
	    	<a href="#">
	        	<img class="img-fluid" src="http://placehold.it/500x300" alt="">
	        </a>
	    </div>
	    <div class="col-md-3 col-sm-6 mb-4">
	      	<a href="#">
	            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
	      	</a>
	    </div>
	    <div class="col-md-3 col-sm-6 mb-4">
	     	<a href="#">
	            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
	        </a>
	    </div>
	    <div class="col-md-3 col-sm-6 mb-4">
	      	<a href="#">
	        	<img class="img-fluid" src="http://placehold.it/500x300" alt="">
	        </a>
	    </div>
	</div>
</div>